### ISSUE TITLE
UnboundLocalError: local variable 'username_check' referenced before assignment

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/wlanpi-chat-bot#26]
Version info:

```bash
wlanpi-chat-bot/bullseye,now 1.0.16-1 arm64 [installed]
```

Config:

```bash
wlanpi@wlanpi-087:~ $ sudo cat /etc/wlanpi-chat-bot/config.json 
{
    "telegram": {
        "bot_token": "<redacted>",
        "chat_id": <redacted>,
        "username": "",
        "display_mode": "full",
        "display_width": "30",
        "yaml_cmds": "/opt/wlanpi-chat-bot/lib/python3.9/site-packages/chatbot/yaml_commands"
    }
}
```

Journal:

```bash
wlanpi@wlanpi-087:~ $ journalctl -u wlanpi-chat-bot
-- Journal begins at Thu 2022-02-17 11:54:56 CST, ends at Thu 2022-02-17 13:45:06 CST. --
Feb 17 13:43:15 wlanpi-087 systemd[1]: Started Telegram chatbot for the WLAN Pi.
Feb 17 13:43:16 wlanpi-087 chatbot[11230]: 2022-02-17 13:43:16,726 [INFO] TelegramAlert: We were offline, but we're back online.
Feb 17 13:43:47 wlanpi-087 chatbot[11230]: Traceback (most recent call last):
Feb 17 13:43:47 wlanpi-087 chatbot[11230]:   File "/usr/sbin/chatbot", line 5, in <module>
Feb 17 13:43:47 wlanpi-087 chatbot[11230]:     from chatbot.__main__ import main
Feb 17 13:43:47 wlanpi-087 chatbot[11230]:   File "/opt/wlanpi-chat-bot/lib/python3.9/site-packages/chatbot/__main__.py", line 5, in <module>
Feb 17 13:43:47 wlanpi-087 chatbot[11230]:     sys.exit(chatbot.main())
Feb 17 13:43:47 wlanpi-087 chatbot[11230]:   File "/opt/wlanpi-chat-bot/lib/python3.9/site-packages/chatbot/chatbot.py", line 315, in main
Feb 17 13:43:47 wlanpi-087 chatbot[11230]:     conf_obj.config["telegram"]["username"] = username_check
Feb 17 13:43:47 wlanpi-087 chatbot[11230]: UnboundLocalError: local variable 'username_check' referenced before assignment
Feb 17 13:43:47 wlanpi-087 systemd[1]: wlanpi-chat-bot.service: Main process exited, code=exited, status=1/FAILURE
Feb 17 13:43:47 wlanpi-087 systemd[1]: wlanpi-chat-bot.service: Failed with result 'exit-code'.
Feb 17 13:43:47 wlanpi-087 systemd[1]: wlanpi-chat-bot.service: Consumed 1.874s CPU time.
Feb 17 13:44:49 wlanpi-087 systemd[1]: Started Telegram chatbot for the WLAN Pi.
Feb 17 13:44:50 wlanpi-087 chatbot[11489]: 2022-02-17 13:44:50,180 [INFO] TelegramAlert: We were offline, but we're back online.
Feb 17 13:44:58 wlanpi-087 chatbot[11489]: Traceback (most recent call last):
Feb 17 13:44:58 wlanpi-087 chatbot[11489]:   File "/usr/sbin/chatbot", line 5, in <module>
Feb 17 13:44:58 wlanpi-087 chatbot[11489]:     from chatbot.__main__ import main
Feb 17 13:44:58 wlanpi-087 chatbot[11489]:   File "/opt/wlanpi-chat-bot/lib/python3.9/site-packages/chatbot/__main__.py", line 5, in <module>
Feb 17 13:44:58 wlanpi-087 chatbot[11489]:     sys.exit(chatbot.main())
Feb 17 13:44:58 wlanpi-087 chatbot[11489]:   File "/opt/wlanpi-chat-bot/lib/python3.9/site-packages/chatbot/chatbot.py", line 326, in main
Feb 17 13:44:58 wlanpi-087 chatbot[11489]:     if (chat_id == chat_id_check) and (username == username_check):
Feb 17 13:44:58 wlanpi-087 chatbot[11489]: UnboundLocalError: local variable 'username_check' referenced before assignment
Feb 17 13:44:58 wlanpi-087 systemd[1]: wlanpi-chat-bot.service: Main process exited, code=exited, status=1/FAILURE
Feb 17 13:44:58 wlanpi-087 systemd[1]: wlanpi-chat-bot.service: Failed with result 'exit-code'.
Feb 17 13:44:58 wlanpi-087 systemd[1]: wlanpi-chat-bot.service: Consumed 1.667s CPU time.
```

**Comment by joshschmelzle** [comment]
I'm filing this as a bug because we get an unhandled traceback when the username config is empty.

The instructions, as is, are not clear that a username is needed.

**Comment by wifinigel** [comment]
As per the user guide, the only field needed is the bot token. 

The chat-id & username are not discussed as they are not user-definable fields - they are completed by the chat-bot program after a valid  key has been entered and the first message is received by the bot.

Tested  as follows:

```
sudo apt install wlanpi-chat-bot
sudo quickstart-chat-bot
# ...enter key as prompted
```
After the process is restarted (by the quickstart script), send the bot 2 "hi" messages, and receive an acknowledgement on the 2nd "hi". Setup complete.

**Comment by joshschmelzle** [comment]
Is the version of chat bot uploaded to packagecloud old?

When I installed from packagecloud, I did send 2 "hi" messages, but did not get an acknowledgement.

That's what triggered me to look at the journal.

**Comment by wifinigel** [comment]
Yes, that is the correct version. I just loaded it and it ran up OK. After the 2 "hi" messages (or any messages TBH) the chat-id & username fields should have values.

**Comment by joshschmelzle** [comment]
Strange. Now I can't reproduce after `sudo apt purge wlanpi-chat-bot`, `sudo apt install walnpi-chat-bot`, and `sudo quickstart-chat-bot`.

**Comment by joshschmelzle** [comment]
Ok, here is the problem. It's when the telegram account does not have a username. 
![image](https://user-images.githubusercontent.com/13954434/154572885-8fb3eaaa-6b86-40af-9787-e8f961929956.png)

**Comment by joshschmelzle** [comment]
So, my statement is the same. The instructions, as is, are not clear that a username is needed. I just didn't clarify that a Telegram username is required.

**Comment by wifinigel** [comment]
OK, updated user guide to include this information.

**Comment by joshschmelzle** [comment]
Thanks the updated docs look good. I do think that the error should be handled in code. Because as is, if the condition is met, the user has to create a telegram username and then 1) know to restart the service or 2) reboot the host. Up to you.

**Comment by wifinigel** [comment]
Good point. I'll also update quickstart to re-initialize the fields so that it can be used in an instance when someone has had a failure or changes their bot details and wants to start over.

May also see if I can get the bot to respond directly to the user with a "You must set your Telegram username" to prompt them directly if the username is missing.
