### ISSUE TITLE
handle wlanpi-release version file change

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/wlanpi-chat-bot#27]
With the change of the wlanpi-release file, https://github.com/WLAN-Pi/pi-gen/commit/7b977a30e3efb59e3f5c1821b6eeb5eb5af6b56f, there is a parsing issue in wlanpi-chat-bot:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/13954434/154561055-ef32b587-bfd1-4617-bbaf-e7e6f1feda9d.png">

Sample fix here: https://github.com/WLAN-Pi/wlanpi-fpms/commit/df6941737ca70e38fae3090be79627a36eae75cd

**Comment by wifinigel** [comment]
Hmmm.....unable to reproduce with a fresh install:

![image](https://user-images.githubusercontent.com/19818404/154569342-d1b7a7e3-bfe7-45be-a9ba-9362b639dc23.png)

**Comment by joshschmelzle** [comment]
Looks like you're running a different image than what I tested on. What is
the contents of /etc/wlanpi-release for that version?

The format of /etc/wlanpi-release was changed in
https://github.com/WLAN-Pi/pi-gen/releases/tag/v3.0.0-rc10

**Comment by wifinigel** [comment]
Can see in code why this may have broken, but do not understand why I don't see it. Applied fix to remove any modification of the version info read from version file & hope this fixed it.

**Comment by wifinigel** [comment]
Also fixed wrong version number in __version.py__
