### ISSUE TITLE
removed from wlanpi 3.1.3?

### ISSUE THREAD

**Issue by nimbo78** [WLAN-Pi/wlanpi-chat-bot#44]
seems like in fresh image there's no more wlanpi-chat-bot? if so - how install it correctly?

```
API key set OK.

Please restart your WLAN Pi for this change to take effect,
or restart the chat-bot service with the command:

   systemctl restart wlanpi-chat-bot

Would you like me to restart the chat-bot service for you now? (y/n): y
Failed to restart wlanpi-chat-bot.service: Unit wlanpi-chat-bot.service not found.
```

**Comment by jiribrejcha** [comment]
`sudo apt install wlanpi-chat-bot` should do the installation trick

And then you can follow the setup guide:
https://github.com/WLAN-Pi/wlanpi-chat-bot/blob/main/docs/USERGUIDE.md#setup
