### ISSUE TITLE
Speedtest command never returns results

### ISSUE THREAD

**Issue by gcastle2007** [WLAN-Pi/wlanpi-chat-bot#46]
Speed test don't work over  chat bot:

I send command: speedtest
and have answer:
📈  Running speedtest...please wait ⏳

and nothing else happens

**Comment by joshschmelzle** [comment]
You need to first install and accept the terms and conditions for the official speedtest binary from Ookla. https://www.speedtest.net/apps/cli

If you want to improve the error handling, PRs are welcome. The code is here: https://github.com/WLAN-Pi/wlanpi-chat-bot/blob/main/chatbot/py_commands/speedtest.py

**Comment by gcastle2007** [comment]
I made this instuction:
## If migrating from prior bintray install instructions please first...
# sudo rm /etc/apt/sources.list.d/speedtest.list
# sudo apt-get update
# sudo apt-get remove speedtest
## Other non-official binaries will conflict with Speedtest CLI
# Example how to remove using apt-get
# sudo apt-get remove speedtest-cli
sudo apt-get install curl
curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
sudo apt-get install speedtest

On console:
wlanpi@wlanpi-359:~ $ speedtest-cli
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: HTTP Error 403: Forbidden
wlanpi@wlanpi-359:~ $

**Comment by gcastle2007** [comment]
I made instruction:
```
## If migrating from prior bintray install instructions please first...
# sudo rm /etc/apt/sources.list.d/speedtest.list
# sudo apt-get update
# sudo apt-get remove speedtest
## Other non-official binaries will conflict with Speedtest CLI
# Example how to remove using apt-get
# sudo apt-get remove speedtest-cli
sudo apt-get install curl
curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
sudo apt-get install speedtest
```

License accepted:
```
Do you accept the license? [type YES to accept]: YES
License acceptance recorded. Continuing.
```

I don't have process after command "speedtest" in bot:
```
wlanpi@wlanpi-359:~ $ ps -ax | grep speedtest
   4769 pts/0    S+     0:00 grep --color=auto speedtest
wlanpi@wlanpi-359:~ $
```
